// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: rpc/gateway.proto

package rpc

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentGateway_StreamChat_FullMethodName = "/gateway.AgentGateway/StreamChat"
)

// AgentGatewayClient is the client API for AgentGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentGatewayClient interface {
	StreamChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatRequest, ChatResponse], error)
}

type agentGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentGatewayClient(cc grpc.ClientConnInterface) AgentGatewayClient {
	return &agentGatewayClient{cc}
}

func (c *agentGatewayClient) StreamChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatRequest, ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentGateway_ServiceDesc.Streams[0], AgentGateway_StreamChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_StreamChatClient = grpc.BidiStreamingClient[ChatRequest, ChatResponse]

// AgentGatewayServer is the server API for AgentGateway service.
// All implementations must embed UnimplementedAgentGatewayServer
// for forward compatibility.
type AgentGatewayServer interface {
	StreamChat(grpc.BidiStreamingServer[ChatRequest, ChatResponse]) error
	mustEmbedUnimplementedAgentGatewayServer()
}

// UnimplementedAgentGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentGatewayServer struct{}

func (UnimplementedAgentGatewayServer) StreamChat(grpc.BidiStreamingServer[ChatRequest, ChatResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamChat not implemented")
}
func (UnimplementedAgentGatewayServer) mustEmbedUnimplementedAgentGatewayServer() {}
func (UnimplementedAgentGatewayServer) testEmbeddedByValue()                      {}

// UnsafeAgentGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentGatewayServer will
// result in compilation errors.
type UnsafeAgentGatewayServer interface {
	mustEmbedUnimplementedAgentGatewayServer()
}

func RegisterAgentGatewayServer(s grpc.ServiceRegistrar, srv AgentGatewayServer) {
	// If the following call panics, it indicates UnimplementedAgentGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentGateway_ServiceDesc, srv)
}

func _AgentGateway_StreamChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentGatewayServer).StreamChat(&grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentGateway_StreamChatServer = grpc.BidiStreamingServer[ChatRequest, ChatResponse]

// AgentGateway_ServiceDesc is the grpc.ServiceDesc for AgentGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.AgentGateway",
	HandlerType: (*AgentGatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChat",
			Handler:       _AgentGateway_StreamChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rpc/gateway.proto",
}
