// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: rpc/gateway.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserQuery     string                 `protobuf:"bytes,2,opt,name=user_query,json=userQuery,proto3" json:"user_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_rpc_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_rpc_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetUserQuery() string {
	if x != nil {
		return x.UserQuery
	}
	return ""
}

type ChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqNum        int32                  `protobuf:"varint,1,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	DeltaText     string                 `protobuf:"bytes,2,opt,name=delta_text,json=deltaText,proto3" json:"delta_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_rpc_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_rpc_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ChatResponse) GetSeqNum() int32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *ChatResponse) GetDeltaText() string {
	if x != nil {
		return x.DeltaText
	}
	return ""
}

var File_rpc_gateway_proto protoreflect.FileDescriptor

const file_rpc_gateway_proto_rawDesc = "" +
	"\n" +
	"\x11rpc/gateway.proto\x12\agateway\"K\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"user_query\x18\x02 \x01(\tR\tuserQuery\"F\n" +
	"\fChatResponse\x12\x17\n" +
	"\aseq_num\x18\x01 \x01(\x05R\x06seqNum\x12\x1d\n" +
	"\n" +
	"delta_text\x18\x02 \x01(\tR\tdeltaText2M\n" +
	"\fAgentGateway\x12=\n" +
	"\n" +
	"StreamChat\x12\x14.gateway.ChatRequest\x1a\x15.gateway.ChatResponse(\x010\x01B\vZ\t./rpc;rpcb\x06proto3"

var (
	file_rpc_gateway_proto_rawDescOnce sync.Once
	file_rpc_gateway_proto_rawDescData []byte
)

func file_rpc_gateway_proto_rawDescGZIP() []byte {
	file_rpc_gateway_proto_rawDescOnce.Do(func() {
		file_rpc_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rpc_gateway_proto_rawDesc), len(file_rpc_gateway_proto_rawDesc)))
	})
	return file_rpc_gateway_proto_rawDescData
}

var file_rpc_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_gateway_proto_goTypes = []any{
	(*ChatRequest)(nil),  // 0: gateway.ChatRequest
	(*ChatResponse)(nil), // 1: gateway.ChatResponse
}
var file_rpc_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.AgentGateway.StreamChat:input_type -> gateway.ChatRequest
	1, // 1: gateway.AgentGateway.StreamChat:output_type -> gateway.ChatResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_gateway_proto_init() }
func file_rpc_gateway_proto_init() {
	if File_rpc_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rpc_gateway_proto_rawDesc), len(file_rpc_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_gateway_proto_goTypes,
		DependencyIndexes: file_rpc_gateway_proto_depIdxs,
		MessageInfos:      file_rpc_gateway_proto_msgTypes,
	}.Build()
	File_rpc_gateway_proto = out.File
	file_rpc_gateway_proto_goTypes = nil
	file_rpc_gateway_proto_depIdxs = nil
}
